label Best_Ending:
    'a'

label Mia_Ending:
    # alarm sfx
    # alarm stop
    "I groggily get out of bed."
    "I haven't felt this tired when I wake up in a while."
    "I check my phone on the side of my bed."
    "06:32"
    "13th September 2024"
    "Wait a minute."
    "It's Friday the 13th. The day after 12th September."
    "I feel tears dropping down my face. I'm finally free from the time loop."
    "I sit in bed for a moment, just taking in the fact that I can finally move on."
    "I glance at my phone again."
    "06:55"
    "Oh no I'll be late for class!"
    "I jumped out of my bed and rushed to the toilet to get ready for school."

    # school bg
    # school bell
    "Phew. I made it to school in time."
    "I haven't been late to school ever since the early days of me being stuck in the time loop."
    "Days? Hours? Times? I don't know and I don't have to care about it anymore."
    "I look at Mia and James's table and see that they both are sitting down at their respective seats."
    "James is talking to Mia but she has a disinterested look in her face."
    "I can barely hear what they are talking about from where I'm sitting."
    b "Mia I'm sorry for what I did. Please forgive me."
    a "We'll talk about it later."
    "She flashes James a smile and looks straight forward."
    "James tried to talk to Mia but quickly recognised his attempts were futile as she was ignoring him."
    "Did Mia actually go through with the idea of breaking up with James?"
    "After seeing Mia break down yesterday after regretting failing to keep in contact with me, she said that she's going to break up with James."
    "It must have been a hasty emotional decision at that time but there's no way she actually is going through with this idea."
    "Random Classmate" "Guys! Ms Ho is arriving!"
    "Ah Physics class."
    "I'd never admit this last time but after spending who knows how long learning Chemistry and Maths over and over again, Physics is a nice change of pace."

    # school bell
    # cafe bg

    "It's recess time."
    "Due to rushing towards school, I didn't get the chance to pack food from home to eat."
    "I was too busy savouring the present."
    $ food = renpy.random.choice(['a', 'b', 'c', 'd'])
    "I head to a stall and order a [food]."
    "I get to buy whatever I want as I don't have to spend time with Mia or James in order to escape the time loop."
    "I sit down a few tables away from where Mia and James usually sit, just so I can confirm that I've finally escaped from the time loop."
    "As I begin to eat, I can hear two familiar voices talking. This time they aren't arguing for once."
    b "Mia, what is it that you want to talk about?"
    a "Later I said."
    b "Well, what do you mean by later?"
    a "After school."
    b "Can't you tell me now?"
    "Mia falls silent."
    a "....no."
    "As I savoured my food, I felt someone tapping my shoulder."
    "I turn around and see Mia. Again."
    m "Mia? What is it?"
    a "Miku....can you come to the school exterior later when school ends?"
    m "What for?"
    a "Well, you'll see later."
    "Mia then left the cafeteria."
    "Well this was unexpected. If anything goes wrong I'll just loop back again."
    "Wait a minute."
    "What if this is just another time loop I'm stuck in?"
    "Oh no. Please don't make that be the case."
    "I try to push these thoughts out of my head and focus on my food. After all, what proof is there that I'm stuck in a time loop."
    "Then again there isn't any proof that I was stuck in a time loop beforehand except my own perspective. From other people's point of view it's just a regular day for them."
    #school bell
    "The sound of the school bell ringing disrupts my thoughts."
    "I head back to the classroom to not be late for classes."

    # class bg
    # school bell
    "Finally school is over for the day."
    "I couldn't pay attention in class. My mind is preoccupied with the feeling that this is still a time loop."
    a "Miku....can you come to the school exterior later when school ends?"
    m "What for?"
    a "Well, you'll see later."
    "I should meet up with Mia after school."

    # outside school bg
    "I head to the school exterior. Mia did ask me to come here. But what for exactly?"
    "I noticed a group of people in a circle. Curious to know why, I went to the circle to find out what is going on."
    "To my surprise, Mia and James are in the middle of the circle."
    a "James, I'm breaking up with you."
    b "....what."
    a "I've been doing some thinking, and I decided that we should break up."
    "Tears stream down Mia's face. It's obvious that it's tough for Mia to do this."
    a "I'm sorry for doing this to you James."
    b "Mia, wait!"
    "James grabs Mia's hand."
    b "Please! Don't go! At least tell me what I did wrong!"
    "Mia stays silent for a while before finally uttering something."
    "James lets go of Mia's hand."
    "Nobody in the crowd could hear it. Fair since it seems really private."
    "Shame that there's a crowd."
    "Speaking of the crowd, the crowd goes livid. They didn't expect to see someone breaking up."
    "James just looks shocked. It doesn't help that there's a crowd that's witnessing this."
    "James then dashes through the crowd, looking pretty hurt."
    "The crowd slowly starts to disperse, leaving only me and Mia."
    a "Ah Miku! You're here!"
    "Mia rushed towards me."
    a "Well originally I wanted only you to see what's happening. Shame that a group has formed though."
    "She looks a bit guilty of what happened."
    m "What did you say to James?"
    a "Well, I told him that we're breaking up and that I've fallen for someone else instead."
    m "Wait, that's why you went through with breaking up with him? Who are you interested in?"
    "Mia came close to me and whispered something into my ear."
    a "You know exactly who it is."
    "I move away from Mia out of shock."
    "I'm confused. I don't really know a lot of people so who is she referring to?"
    a "Anyways I'mma go now. See you soon."
    "Mia leaves the school."
    "I just stand there in confusion."
    "I hear someone approaching me and I come face to face with Sarah,one of Mia's new friends, and the person who sits next to me in class."
    s "Hehehehe."
    s "Good job. Now what's rightfully mine is now available."
    s "You did good Hatsune Miku. You're now free."
    m "Wait, Sarah! What do you mean?"
    "I try to call out to her but she had already left the scene."
    "What did she mean by what she said? What is even going on."
    "I decide to go back home. There's not much for me to do now."

    # room bg
    "It's almost midnight."
    "I lie in bed just thinking about what went on."
    "I also can't stop thinking about if I'm still stuck in a time loop."
    "I can't sleep due to being very restless."
    "I look at my phone to check the time."
    "23:59"
    "1 more minute until I'll find out."
    "Bracing to fall unconscious, I lie still in bed."
    "...."
    "...."
    "I'm still awake."
    "I look at my phone."
    "00:04"
    "15 September 2024."
    "In disbelief I look at my phone again."
    "The same thing is shown on the screen."
    "I did it."
    "I finally left this cursed time loop."
    "I can feel myself crying."

    # transtion

    "The next thing I know, I wake up in my bed, sunlight coming out from the windows."
    "I look at my phone and see that I've gotten text messages from none other than Mia."
    a "hey miku!"
    a "do you wanna date tmr?"
    a "*hang out"
    a 'i meant hang out'
    "I put my phone away and contemplate what is going on."
    "I can finally live life normally and I'm friends with Mia again."
    "Things are finally looking up."

    # transioton
    "The next day arrived."
    "I get dressed to hang out with Mia."
    "Or more accurately, my date."
    "I'm not 100% sure."
    "I head out of my room in order to face the future head on."
    return

label James_Ending:
    # alarm sfx
    # alarm stop
    "I groggily get out of bed."
    "I haven't felt this tired when I wake up in a while."
    "I check my phone on the side of my bed."
    "06:32"
    "13th September 2024"
    "Wait a minute."
    "It's Friday the 13th. The day after 12th September."
    "I feel tears dropping down my face. I'm finally free from the time loop."
    "I sit in bed for a moment, just taking in the fact that I can finally move on."
    "I glance at my phone again."
    "06:55"
    "Oh no I'll be late for class!"
    "I jumped out of my bed and rushed to the toilet to get ready for school."

    # school bg
    # school bell
    "Phew. I made it to school in time."
    "I haven't been late to school ever since the early days of me being stuck in the time loop."
    "Days? Hours? Times? I don't know and I don't have to care about it anymore."
    "I look at Mia and James's table and see only Mia is at her seat. James is nowhere to be seen."
    "After a while, James suddenly burst into the classroom."
    b "Mia! I'm gonna change seats."
    a "W-what? What do you mean?"
    b "I said that I'm changing seats."
    a "You can't do that! Besides, the teachers won't let you."
    b "I already asked for permission. And our class teacher let me."
    a "You what???"
    "James pointed to the person sitting beside me."
    b "You! Swap places with me!"
    "The person sitting there stuttered nervously before bringing his belongings to James's table."
    "James heads on over to where that guy was originally."
    "Mia could only stare in disbelief on what's happening."
    b "Hey Miku!"
    "James is beaming at me. Is he thinking about his crush on me?"
    "Random Classmate" "Guys! Ms Ho is arriving!"
    "Ah Physics class."
    "I'd never admit this last time but after spending who knows how long learning Chemistry and Maths over and over again, Physics is a nice change of pace."

    # school bell
    # cafe bg

    "It's recess time."
    "Due to rushing towards school, I didn't get the chance to pack food from home to eat."
    "I was too busy savouring the present."
    $ food = renpy.random.choice(['a', 'b', 'c', 'd'])
    "I head to a stall and order a [food]."
    "I get to buy whatever I want as I don't have to spend time with Mia or James in order to escape the time loop."
    "I sit down a few tables away from where Mia and James usually sit, just so I can confirm that I've finally escaped from the time loop."
    "As I begin to eat, I can hear two familiar voices talking. This time they aren't arguing for once."
    a "James why did you do what you did earlier?"
    b "I'll tell you after school."
    a "Can't you tell me now?"
    b "I can't let the prized student suffer during class. At least I'm doing it before the weekend."
    "As I savoured my food, I felt someone tapping my shoulder."
    "I turn around and see James"
    m "James? What is it?"
    b "Hey Miku, can you come to the school exterior after school ends?"
    m "What for?"
    b "Well, you'll see later."
    "Mia then left the cafeteria."
    "Well this was unexpected. If anything goes wrong I'll just loop back again."
    "Wait a minute."
    "What if this is just another time loop I'm stuck in?"
    "Oh no. Please don't make that be the case."
    "I try to push these thoughts out of my head and focus on my food. After all, what proof is there that I'm stuck in a time loop."
    "Then again there isn't any proof that I was stuck in a time loop beforehand except my own perspective. From other people's point of view it's just a regular day for them."
    #school bell
    "The sound of the school bell ringing disrupts my thoughts."
    "I head back to the classroom to not be late for classes."

    # class bg
    # school bell
    "Finally school is over for the day."
    "I couldn't pay attention in class. My mind is preoccupied with the feeling that this is still a time loop."
    b "Hey Miku, can you come to the school exterior after school ends?"
    m "What for?"
    b "Well, you'll see later."
    "I should meet up with James after school."

    # outside school bg
    "I head to the school exterior. James did ask me to come here. But what for exactly?"
    "I noticed a group of people in a circle. Curious to know why, I went to the circle to find out what is going on."
    "To my surprise, Mia and James are in the middle of the circle."
    b "Mia, I wanna break up with you."
    a "James? What are you talking about?"
    b "Like I said, I wanna break up with you."
    a "Wh-why?"
    b "Well, I fell in love with someone else. "
    "The crowd goes livid. They didn't expect to see someone breaking up. Much less James having a crush on someone else."
    "Mia looks very hurt. Doesn't help that there's a crowd watching this."
    "Mia rushes away, crying."
    "The crowd slowly starts to disperse, leaving only me and James."
    b "Miku,you're here."
    "James walked over towards me."
    b "Shame there was a group earlier, I wanted you to be the only spectator."
    "He looks a bit guilty of what happened."
    m "It's because you like me huh."
    b "Yeah."
    b "Miku, what do you think of me?"
    "This thought has plagued me since the first time I heard him say it and I finally know the answer."
    m "I like you James I really do."
    "James was ecstatic."
    b "Oh wow, I'm glad."
    b "So shall we go on a date on Sunday?"
    "I can't tell him that I might be stuck in a loop."
    m "Yeah alright then."
    b "Alright!"
    "James grasps my hands."
    b "You have no idea what this means to me."
    "James lets go and waves towards me."
    b "Bye Mia! See you on Sunday!"
    "James leaves the school."
    "I just stood there in surprise."
    "I hear someone approaching me and I come face to face with Sarah,one of Mia's new friends, and the person who sits next to me in class."
    "She has a furious look on her face."
    s "This can't be happening. Nonononono."
    s "He was supposed to be with me! Not you!"
    s "All that effort just for nothing!"
    "Hatsune Miku! Don't relax just yet. I'll get you someday."
    m "Wait, Sarah! What do you mean?"
    "I try to call out to her but she had already left the scene."
    "What did she mean by what she said? What is even going on."
    "I decide to go back home. There's not much for me to do now."

    # room bg
    "It's almost midnight."
    "I lie in bed just thinking about what went on."
    "I also can't stop thinking about if I'm still stuck in a time loop."
    "I can't sleep due to being very restless."
    "I look at my phone to check the time."
    "23:59"
    "1 more minute until I'll find out."
    "Bracing to fall unconscious, I lie still in bed."
    "...."
    "...."
    "I'm still awake."
    "I look at my phone."
    "00:04"
    "15 September 2024."
    "In disbelief I look at my phone again."
    "The same thing is shown on the screen."
    "I did it."
    "I finally left this cursed time loop."
    "I can feel myself crying."

    # transtion

    "The next thing I know, I wake up in my bed, sunlight coming out from the windows."
    "I look at my phone and see someone calling me. The caller id is unknown."
    "I pick up the phone and hear James talking on the other side of the phone."
    b "Hey Miku!"
    b "Well, this is Miku, right?"
    m "Yeah it's Miku."
    b "Ah great, I just wanted to call you so I can confirm this is your number."
    "James promptly hung up the phone."
    "I'd usually be annoyed at this but not today."
    "I put my phone away and contemplate what is going on."
    "I can finally live life normally and I'm dating James."
    "Things are finally looking up."

    # transioton
    "The next day arrived."
    "I get dressed for my date with James."
    "I head out of my room in order to face the future head on."
    return

label Bad_Ending:
    'a'

label Secret_Ending:
    'a'